apps/login_register/urls.py
from django.conf.urls import url
from . import views


# login urls

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^peek/$', views.peek, name='peek'),
]

klassholes/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login_register.urls', namespace='login_register')),
    url(r'^dashboard/', include('apps.dashboard.urls', namespace='dashboard')),
    url(r'^quotes/', include('apps.quotes.urls', namespace='quotes')),
    url(r'^admin/', admin.site.urls),
]

apps/login_register/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import datetime
import bcrypt


# Create your models here.

class UserManager(models.Manager):
    def register_validator(self, postData):
        errors = {}
        now = datetime.datetime.now()
        year = now.year
        birth_year = postData['dob'][:4]

        if len(postData['name']) < 2:
            errors['name'] = "Must enter name"
        if len(postData['alias']) < 2:
            errors['alias'] = "Must enter an Alias"
        if len(postData['email']) < 2:
            errors['email'] = "Must enter an email"
        elif int(year) - int(birth_year) < 18:
            errors['age_restriction'] = "You are too young my child..."
        if len(postData['dob']) < 2:
            errors['dob'] = "Must enter a DOB"
        if len(postData['password']) < 2:
            errors['password'] = "Must enter password"
        if postData['password'] != postData['confirm_password']:
            errors['pass_match'] = "Passwords do not match"
        if User.objects.filter(email=postData['email']).exists():
            errors['email_exists'] = "That email already exists! Please try again..."
        return errors



class UserManager_login(models.Manager):
    def login_validator(self, postData):
        errors = {}
        if len(postData['email']) < 2:
            errors['email'] = "Must enter an email"
        if len(postData['password']) < 2:
            errors['password'] = "Must enter password"
        if len(errors):
            return errors

        if User.objects.filter(email=postData['email']).exists():
            user = User.objects.get(email=postData['email'])
        else:
            errors['email_not_exists'] = "That email doesn't exist"
            return errors

        db_password = user.password
        login_password = postData['password']
# **** I put the Try Excpet here because a few of the users I created have plain text passwords and it trips a Salt error here ****
        try:
            bcrypt.checkpw(login_password.encode(), db_password.encode())
        except ValueError as e:
            errors['something_went_wrong'] = "Something went wrong..."
            return errors

        if bcrypt.checkpw(login_password.encode(), db_password.encode()) == False:
            errors['password_incorrect'] = "Password is incorrect"
            return errors
        else:
            return

class QuoteManager(models.Manager):
    def quote_validator(self, postData):
        errors = {}
        if len(postData['content_by']) < 2:
            errors['content_by'] = "Yo.. I don't know anyone without a name... Try again there buddy."
        if len(postData['message']) < 10:
            errors['message'] = "That was not a quote..."
        return errors




class User(models.Model):
    name = models.CharField(max_length=255)
    alias = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    dob = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()
    objectsTwo = UserManager_login()

    def __str__(self):
        return ('Name: {}.. Alias: {}.. Email: {}..').format(self.name, self.alias, self.email)

class Quote(models.Model):
    content_by = models.CharField(max_length=255)
    content = models.TextField(max_length=300)
    user = models.ForeignKey(User, related_name='quotes')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = QuoteManager()

    def __str__(self):
        return ('By: {}.. Quote: {}..').format(self.content_by, self.content)

class Favorite(models.Model):
    user = models.ForeignKey(User, related_name='user_favorite')
    quote = models.ForeignKey(Quote, related_name='quotes_info')
    # def __str__(self):
    #     return "User {}... Quote: {}".format(self.user, self.quote)

apps/login_register/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .models import *
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls import reverse
import bcrypt
import datetime

# Create your views here.

# ****** login views *********

def index(request):

    template ='login_register/login_register.html'
    return render(request, template)





# ***Process the registration data****

def register(request):
    if request.method == "POST":

        name = request.POST['name']
        alias = request.POST['alias']
        email = request.POST['email']
        password = request.POST['password']
        dob = request.POST['dob']

        form_errors = User.objects.register_validator(request.POST)

        if len(form_errors):
            for tag, error in form_errors.iteritems():
                messages.error(request, error, extra_tags=tag)
            return redirect(reverse('login_register:index'))


        db_password = bcrypt.hashpw(request.POST['password'].encode(), bcrypt.gensalt())

# ***Not 100% sure if I should create users in the views when it could be done in the manager...
# ***But then again isn't the manager for validations only?***

        User.objects.create(
            name=name,
            alias=alias,
            email=email,
            password=db_password,
            dob=dob,
        )
        messages.success(request, "Thank you for registering!")
        messages.success(request, "Please login to access the site")
        return redirect(reverse('login_register:index'))

    else:
        messages.error(request, "No No No! You cannot bypass my python!... If you can email me bro...")
        return redirect(reverse('login_register:index'))

    return redirect(reverse('login_register:index'))









def login(request):
    if request.method == "POST":
        errors = User.objectsTwo.login_validator(request.POST)

        if errors != None:
            if len(errors):
                for tag, error in errors.iteritems():
                    messages.error(request, error, extra_tags=tag)
                return redirect(reverse('login_register:index'))

        user = User.objects.get(email=request.POST['email'])
        user_id = user.id
        user_name = user.name

        request.session['user_id'] = user_id
        request.session['user_name'] = user_name
        request.session['logged_in'] = 'logged_in'

        return redirect(reverse('dashboard:index'))

    return redirect(reverse('login_register:index'))







def logout(request):
    del request.session['logged_in']
    del request.session['user_name']
    del request.session['user_id']
    return redirect('login_register:index')








# Just gives data so I can see the database.

def peek(request):
    context = {
        'users':User.objects.all().values(),

    }
    template = 'login_register/peek.html'
    return render(request, template, context)

apps/login_register/templates/login_register/login_register.html
{% extends "dashboard/dashboard.html" %}

{% block title %} Get In Here! {% endblock %}

{% block content %}

<!-- {% load static %} -->

<br>
<div class="container-fluid">
     <div class="jumbotron login_jumbo">
          <div class="row">
               <div class="col-lg-8">
                    <h1 style="color:white">
                         Welcome To The Klasshole!
                    </h1>
                    <h6 style="color:white">
                         Let your inner Klasshole out...
                    </h6>
               </div>
               <div class="col-lg-4">
                    <!-- img on the jumbotron -->
                    <img src="{% static 'login_register/images/klasshole.jpg' %}" class="img-fluid klassimg" alt="klasshole">
               </div>
          </div>
     </div>

     <div class="row">
          <div class="col-lg-12">
               {% if messages %}
               <div class="container">
                    <ul class="messages">
                   {% for message in messages %}
                        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                   {% endfor %}
                   </ul>
               </div>
               {% endif %}
          </div>
     </div>
</div>

<br>
<br>

<div class="container">
     <div class="row">
          <div class="col-lg-5 register">
               <h1><small>Register</small></h1>
               <hr>
               <form class="" action="{% url 'login_register:register' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group row">
                         <label for="name" class="col-2 col-form-label">Name </label>
                         <div class="col-10">
                              <input type="text" class="form-control" name="name" value="">
                         </div>
                    </div>
                    <div class="form-group row">
                         <label for="alias" class="col-2 col-form-label">Alias </label>
                         <div class="col-10">
                              <input type="text" class="form-control" name="alias" value="">
                         </div>
                    </div>
                    <div class="form-group row">
                         <label for="email" class="col-2 col-form-label">Email </label>
                         <div class="col-10">
                              <input type="email" class="form-control" name="email" data-error="Bruh, that email address is invalid" value="">
                         </div>
                    </div>
                    <div class="form-group row">
                         <label for="password" class="col-2 col-form-label">Password </label>
                         <div class="col-10">
                              <input type="password" class="form-control" name="password" value="">
                         </div>
                    </div>
                    <div class="form-group row">
                         <label for="confirm_password" class="col-2 col-form-label">Confirm </label>
                         <div class="col-10">
                              <input type="password" class="form-control" name="confirm_password" value="">
                         </div>
                    </div>
                    <p>*If Password isn't 8 characters long... This will blow up*</p>
                    <div class="form-group row">
                         <label for="dob" class="col-2 col-form-label">DOB </label>
                         <div class="col-10">
                              <input type="date" class="form-control" name="dob" value="">
                         </div>
                    </div>
                    <input type="submit" name="" class="btn float-right" value="Register">
               </form>
          </div>

          <div class="col-lg-5 login">
               <h1><small>Login</small></h1>
               <hr>
               <form class="" action="{% url 'login_register:login' %}" method="post">
                    {% csrf_token %}

                    <div class="form-group row">
                         <label for="email" class="col-2 col-form-label">Email </label>
                         <div class="col-10">
                              <input type="text" class="form-control" name="email" value="">
                         </div>
                    </div>
                    <div class="form-group row">
                         <label for="password" class="col-2 col-form-label">Password </label>
                         <div class="col-10">
                              <input type="password" class="form-control" name="password" value="">
                         </div>
                    </div>
                    <input type="submit" name="" class="btn float-right" value="Login">
               </form>
          </div>
     </div>
</div>
<br>

{% endblock content %}

apps/login_register/templates/login_register/peek.html
{% extends "dashboard/dashboard.html" %}

{% block title %} Peek {% endblock %}

{% block content %}


     <!-- <div class="container">
{% for user in users %}
     <p>U:{{user.name}} A:{{user.alias}}</p>
{% endfor %}
     </div> -->


     {{users}}

{% endblock content %}