apps/dashboard/urls.py
from django.conf.urls import url
from . import views


# dashboard urls

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add_quote/$', views.add_quote, name='add_quote'),
    url(r'^add_favorite/(?P<quote_id>\d+)/', views.add_favorite, name='add_favorite'),
    url(r'^remove_favorite/(?P<fav_id>\d+)/', views.remove_favorite, name='remove_favorite'),

]

apps/login_register/urls.py
from django.conf.urls import url
from . import views


# login urls

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^peek/$', views.peek, name='peek'),
]

klassholes/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.login_register.urls', namespace='login_register')),
    url(r'^dashboard/', include('apps.dashboard.urls', namespace='dashboard')),
    url(r'^quotes/', include('apps.quotes.urls', namespace='quotes')),
    url(r'^admin/', admin.site.urls),
]

apps/dashboard/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

apps/dashboard/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib import messages
from django.shortcuts import render, redirect
from ..login_register.models import *

# Create your views here.

# ******** dashboard views *********

def index(request):
    if 'logged_in' not in request.session:
        messages.error(request, 'Hey Klasshole... You need to Login or Register to access that')
        return redirect('login_register:index')

    favs = User.objects.get(id=request.session['user_id']).user_favorite.all().values_list('quote_id', flat = True)

    quotes = Quote.objects.exclude(id__in=favs)

    context = {
        'quotes':quotes,
        'user_favorites':User.objects.get(id=request.session['user_id']).user_favorite.all(),
    }

    template = 'dashboard/dashboard.html'
    return render(request, template, context)










def add_quote(request):
    if 'logged_in' not in request.session:
        messages.error(request, 'Hey Klasshole... You need to Login or Register to access that')
        return redirect('login_register:index')

    if request.method == "POST":
        errors = Quote.objects.quote_validator(request.POST)

        if len(errors):
            for tag, error in errors.iteritems():
                messages.error(request, error, extra_tags=tag)
            return redirect('dashboard:index')

        content_by = request.POST['content_by']
        message = request.POST['message']
        user = User.objects.get(id=request.session['user_id'])

        Quote.objects.create(content_by=content_by,content=message,user=user)


        print content_by
        print message

        return redirect('dashboard:index')

    return redirect('dashboard:index')










def add_favorite(request, quote_id):
    if 'logged_in' not in request.session:
        messages.error(request, 'Hey Klasshole... You need to Login or Register to access that')
        return redirect('login_register:index')

    if request.method == "POST":

        # quote = quote_id
        user = User.objects.get(id=request.session['user_id'])
        quote = Quote.objects.get(id=quote_id)

        Favorite.objects.create(user=user,quote=quote)

        return redirect('dashboard:index')








def remove_favorite(request, fav_id):

    if 'logged_in' not in request.session:
        messages.error(request, 'Hey Klasshole... You need to Login or Register to access that')
        return redirect('login_register:index')

    if request.method == "POST":

        user = User.objects.get(id=request.session['user_id'])

        favorite = user.user_favorite.get(id=fav_id).delete()

        return redirect('dashboard:index')

    messages.error(request, 'Woah... Something went wrong')
    return redirect('login_register:index')

apps/dashboard/templates/dashboard/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <meta http-equiv="X-UA-Compatible" content="ie=edge">
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
     {% load static %}
     <link rel="stylesheet" href="{% static 'dashboard/css/style.css' %}">
     <title>{% block title %}KlassHole Dashboard{% endblock %}</title>
</head>
<body>
     <div class="container-fluid">
          <nav class="navbar navbar-inverse bg-inverse">
               <div class="col-lg-4">
                    <div class="input-group">
                         <span class="input-group-btn">
                              <button class="btn" type="button">Go!</button>
                         </span>
                         <input type="text" class="form-control" placeholder="This is an illusion...">
                    </div>
               </div>
               <div class="navbar">
                    <a class="nav-item nav-link" href="{% url 'dashboard:index' %}">Dashboard</a>
                    <a class="nav-item nav-link" href="{% url 'login_register:peek' %}">Peek</a>
                    <a class="nav-item nav-link" href="{% url 'login_register:index' %}">Register</a>

                    {% if request.session.logged_in %}
                    <a class="nav-item nav-link" href="{% url 'login_register:logout' %}">Logout</a>
                    {% endif %}

               </div>
          </nav>
     </div>

     <div class="container-fluid">
          <div id="content">

{% block content %}


          <!-- ******** jumbotron ******** -->
          
               <div class="container-fluid">
                    <div class="jumbotron login_jumbo">
                         <h1 style="color:white">Welcome, {{request.session.user_name}}</h1>
                    </div>
               </div>

               {% if messages %}
               <div class="container">
                    <div class="row">
                         <div class="col-lg-12">

                         {% for message in messages %}
                              <h1 class="text-center">{{ message }}</h1>
                         {% endfor %}

                         </div>
               {% endif %}

                    </div>
               </div>


     <!-- ******** One row for titles of containers in order to keep them out of the scroll box ******* -->

               <div class="container">
                    <div class="row">
                         <div class="col-md-6">
                              <h4>Here are the Quotes bro</h4>
                              <hr>
                         </div>
                         <div class="col-md-6">
                              <h4>Favorites</h4>
                              <hr>
                         </div>
                    </div>

          <!-- ********* One row with the quotes and fav_quotes split up ********** -->

                    <div class="row">
                         <div class="col-lg-6 quote_favs">

                              {% for quote in quotes %}
                              <div class="row">
                                   <div class="col-md-10">
                                        <h6>{{quote.content_by}}: <small>{{quote.content}}</small></h6>
                                        <small>Posted By:<a href="{% url 'quotes:index' quote.user.id %}">{{quote.user.name}}</a></small>
                                        <form class="" action="{% url 'dashboard:add_favorite' quote.id %}" method="post">
                                             {% csrf_token %}
                                             <small><input type="submit" class="btn btn-info float-right" name="" value="Add To My Favorties"></small>
                                        </form>
                                   </div>
                              </div>
                              <hr>
                              {% endfor %}

                         </div>

                         <div class="col-lg-6 quote_favs">

                              {% for fav in user_favorites %}
                              <div class="row">
                                   <div class="col-md-10">
                                        <h6>{{fav.quote.content_by}}: <small>{{fav.quote.content}}</small></h6>
                                        <small>Posted By:<a href="{% url 'quotes:index' fav.quote.user.id %}">{{fav.quote.user.name}}</a></small>
                                        <form class="" action="{% url 'dashboard:remove_favorite' fav.id %}" method="post">
                                             {% csrf_token %}
                                             <small><input type="submit" class="btn btn-info float-right" name="" value="Remove from Favorties"></small>
                                        </form>
                                   </div>
                              </div>
                              <hr>
                              {% endfor %}

                         </div>
                    </div>




                    <div class="row">
                         <div class="col-lg-6">
<!-- I am not an expert on the grid system yet so this is to take space in order for the add quote box to "float right" -->
                         </div>


          <!-- ******* Add quote form ******** -->
                         <div class="col-lg-6 quote">
                              <h4>Contribute a quote</h4>
                              <form class="" action="{% url 'dashboard:add_quote' %}" method="post">
                                   {% csrf_token %}
                                   <div class="form-group row">
                                        <label for="content_by" class="col-3 col-form-label">Quote By: </label>
                                        <div class="col-9">
                                             <input type="text" class="form-control" name="content_by" value="">
                                        </div>
                                   </div>
                                   <div class="form-group row">
                                        <label for="message" class="col-2 col-form-label">Quote: </label>
                                        <div class="col-10">
                                             <textarea name="message" class="form-control" rows="5" cols="10"></textarea>
                                        </div>
                                   </div>
                                   <input type="submit" name="" class="btn-success float-right" value="Add Quote">
                              </form>
                         </div>
                    </div>
               </div>

{% endblock content %}

          </div>
     </div>

     <br>
     <hr>

     <div class="container-fluid">
          <div class="row">
               <div class="col-md-4">
                    <div class="card-block">
                         <h4>Address</h4>
                         <p>6666 No way ln</p>
                         <p>Nowhere Texas 75034</p>
                         <p>"Don't check me out"</p>
                    </div>
               </div>
               <div class="col-md-4">
                    <div class="card-block">
                         <h4>Social Media</h4>
                         <p>Twitter: </p>
                         <p>Facebook: </p>
                         <p>Instagram: </p>
                    </div>
               </div>
               <div class="col-md-4">
                    <div class="card-block">
                         <h4>Contact</h4>
                         <p>Email:</p>
                         <p>The Door:</p>
                    </div>
               </div>

          </div>
     </div>
     <br>
     <br>
</body>
</html>